### PR TITLE
Update repository link

### PR DESCRIPTION
**Pull request by jhriv**
Repository has been transfered to ucsdlib

### CODE REVIEW

**Comment by jhriv** [comment]
@ucsdlib/developers   Please review - transferred the repo earlier

**Comment by VivianChu** [comment]
👍

**Review by lsitu — APPROVED** [review]

**Review by lsitu — APPROVED** [review]

**Comment by lsitu** [comment]
👍 @jhriv It looks like I can't approve and merge it.

**Comment by mcritchlow** [comment]
@ucsdlib/developers access control should be setup properly now on this repo. If you notice anything else, please let me know.

**Comment by hweng** [comment]
:+1:

**Pull request merged**
