### PR TITLE
Fix add object/item problem

### LINKED ISSUE #6: Cannot add item/object
**ISSUE:**
- As admin, when I add an **item** (Curation, upload image, enter metadata, save), I receive an Object loaded successfully message, but I cannot see/retrieve the object in the UI.

### PR DESCRIPTION
**Pull request by VivianChu**
Fixes #6  ; refs #6 

Fix create new item/object problem. User cannot retrieve the object in the UI.

Changes proposed in this pull request:
*Update ruby
*Add Imagemagick and riiif gem

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by jhriv** [comment]
Imagemagick isn't a "build dep", but it is an "additional dep", otherwise looks good to me.


[install.yml.diff.txt](https://github.com/ucsdlib/spotlight-demo/files/920364/install.yml.diff.txt)

**Comment by VivianChu** [comment]
@jhriv - I move imagemagick to the additional dep section and it works fine.

**Comment by jhriv** [comment]
Was removing the blank line intentional?

**Comment by VivianChu** [comment]
No

**Comment by jhriv** [comment]
Do you want to put it back, to keep the changes smaller?

**Comment by jhriv** [comment]
You can squash all the commits into one, and re-push the branch, if you want to keep history a little cleaner and clearer

**Comment by VivianChu** [comment]
@jhriv - The commits have been squashed.

**Review by jhriv — APPROVED** [review]
Looks good! Thanks

**Pull request merged**
